### ISSUE TITLE
ETH price not loading

### ISSUE THREAD

**Issue by brocktice** [metanull-operator/eth2-ubuntu#10]
Hi, I followed your Ubuntu 20.02 instructions and I am not getting the ETH price in the dashboard, nor any of the dependent fields.

I get the following message from json_exporter logs:

`json_exporter[72454]: level=error ts=2021-02-16T21:29:29.312Z caller=collector.go:63 msg="Failed to convert extracted value to float64" path=$.ethereum.usd value=$.ethereum.usd err="strconv.ParseFloat: parsing \"$.ethereum.usd\": invalid syntax; strconv.ParseBool: parsing \"$.ethereum.usd\": invalid syntax" metric="Desc{fqName: \"ethusd\", help: \"Ethereum (ETH) price in USD\", constLabels: {}, variableLabels: []}"`

My json_exporter.yml contents are:
```
metrics:
- name: ethusd
  path: $.ethereum.usd
  help: Ethereum (ETH) price in USD
```
I've noticed that in some of your instructions you have path: {.ethereum.usd} but when I use this, json_exporter fails to start with message:

`msg="Error loading config" err="yaml: unmarshal errors:\n  line 3: cannot unmarshal !!map into string"`

Unfortunately these are tools I'm not familiar with so I'm having some trouble figuring out where the problem lies.

**Comment by metanull-operator** [comment]
Thanks for the report. json_exporter was recently updated to use a new syntax for their JSON queries. Please edit your json_exporter.yml file so that the "path" line reads `  path: {.ethereum.usd}` instead of the current value. I will update this documentation now.

**Comment by brocktice** [comment]
Per the original ticket, ```path: {.ethereum.usd}``` produces the following log output and ```json_exporter``` fails to start:

`msg="Error loading config" err="yaml: unmarshal errors:\n  line 3: cannot unmarshal !!map into string"`

**Comment by brocktice** [comment]
OK I solved it by using quotes: ```path: "{.ethereum.usd}"```

**Comment by metanull-operator** [comment]
Looks like you are correct. I just double-checked my working example and it does have quotes. Thanks for the update. I will update documentation accordingly.
