### ISSUE TITLE
Is the any process to create operator and prunning for geth?

### ISSUE THREAD

**Issue by toraonion** [metanull-operator/eth2-ubuntu#13]
Hi, thank you for super extensive guide to setup eth node. I helped me a lot in learning about eth2 beacon and stuff.

I wonder with this setup, is there anyway we can set operator? and any guide for pruning geth, since it took over 800gb in my machine.

Or is there any guide to set up reverse proxy to enable https and wss endpoint from the node. I haven't found any usable guide that can help.

Thank you.

**Comment by metanull-operator** [comment]
What do you mean by set operator?

I am sure I can put something together for pruning geth, but other geth pruning guides may also work with a few minor adjustments.

I have not worked with reverse proxies at all. How will you be using it?

**Comment by metanull-operator** [comment]
Try this: https://github.com/metanull-operator/eth2-ubuntu/blob/master/prune_geth.md

**Comment by peteral2** [comment]
hi, all , if I need to prune geth , then I need to stop geth and get punished. "There are penalties, which cost ETH, for going offline"
right? thanks
