### ISSUE TITLE
MEV-Boost

### ISSUE THREAD

**Issue by mtxmomoaudio** [metanull-operator/eth2-ubuntu#14]
Any instructions for setting up mev-boost now that the Flashbots relay is live?

**Comment by metanull-operator** [comment]
I should have something by tomorrow.

**Comment by metanull-operator** [comment]
Instructions for MEV-Boost are now available.

If you installed with my original instructions pre-July 19, 2022, then you installed with v1 of my instructions and want to use the following to set up MEV-Boost.

https://github.com/metanull-operator/eth2-ubuntu/blob/master/v1/mev-boost.md

If you installed after July 19, 2022, then you installed with v2 of my instructions and you will want to use the following to set up MEV-Boost.

https://github.com/metanull-operator/eth2-ubuntu/blob/master/v2/mev-boost.md

Open a new issue if you have any problems using these instructions.
