### ISSUE TITLE
Question on backups 

### ISSUE THREAD

**Issue by guirkgumbo** [metanull-operator/eth2-ubuntu#15]
Curious on how you are doing backups. Are you doing just prysm approach via their docs or something more?

**Comment by metanull-operator** [comment]
I am not doing backups. I have my keys backed up in multiple places. I have considered backing up the chains, but I was concerned about the size of the transfers involved and any potential performance hits. I haven't gotten around to doing tests to see whether or not performance would actually be a problem, or to look at any innovative ways of backing up.

I also know that spinning up a new system wouldn't take me long, personally. Syncing would be a problem. Sometimes I have a secondary system that is synced to mainnet as a backup, but that same system is often synced to testnets too. So not a reliable fallback.

I may start looking more into it in the future, and I welcome any wisdom you find that may help.

**Comment by guirkgumbo** [comment]
Thanks for the reply!
I don't have anything concrete yet but I hope to share what I end up going with.
Slashing protection will be an important nuance if any system does go down.
https://docs.prylabs.network/docs/wallet/slashing-protection
