### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by redamoukh** [metanull-operator/eth2-ubuntu#16]
Missing step; after changes you need to reload the config 
sudo systemctl daemon-reload

**Comment by metanull-operator** [comment]
Could you provide a little more context please. Which instructions are you looking at? Which step needs the reload?

**Comment by metanull-operator** [comment]
If this happens to be able the MEV-Boost instructions, note that these instructions were written under the assumption that the Prysm configuration is being set in a YAML file. With a YAML file, no "daemon-reload" is required. Nevertheless, I will add something addressing those people who are using systemd for all Prysm config.

**Comment by redamoukh** [comment]
you're right, not needed if YAML file is used for the config
