### ISSUE TITLE
Add Firmware/BIOS updating info

### ISSUE THREAD

**Issue by NewsGuyTor** [metanull-operator/eth2-ubuntu#2]
Awesome guide, thanks! I plan to follow it shortly when my own NUC and components arrive.

One suggestion though, you should add instructions about the need to update the firmware/BIOS of the NUC and SSD, otherwise I think many people will run old versions without knowing it. The NUC8 received an important BIOS update for the fan in August for example.

**Comment by metanull-operator** [comment]
Thanks for the feedback. I have added a section for the BIOS with links to Intel's documentation.
