### ISSUE TITLE
How to remove a validator key

### ISSUE THREAD

**Issue by mtxmomoaudio** [metanull-operator/eth2-ubuntu#20]
Switching one of my validators over to Rocketpool, and I need to remove one of the keys. (V1) 

I see under /home/validator/.eth_validators/prysm_v2/direct/all-accounts.keystore.json but not sure how to modify it?
I think it was just for creating deposits, but I also deleted the wanted .json from /home/user/eth2deposit-cli.

Restarting validator still shows it's attesting to it.

**Comment by metanull-operator** [comment]
Have you tried the `validator accounts delete` command? I have not used it myself, but it appears it will ask you which keys you would like to remove.

I found a reference to it here: https://docs.prylabs.network/docs/advanced/migrating-keys#step-5--verification-and-restarting-the-validator-client

If that isn't enough to get you going on this, let me know and I'll look into it more.

**Comment by mtxmomoaudio** [comment]
Thanks for the quick response. That's what I needed. 
From the /home/beacon/bin directory I ran 'sudo ./prysm.sh validator accounts delete --wallet-dir=/home/validator/.eth2validators/prysm-wallet-v2'
It looks like it downloaded Prysm and I had to accept it's terms, but then it listed which accounts to delete (you have to use the up and down arrows to select the right one and hit enter when it displays the right one, then enter again when "done selecting" was shown to close the prompt).
Then I ran 'sudo ./prysm.sh validator accounts list --wallet-dir=/home/validator/.eth2validators/prysm-wallet-v2' to confirm it was no longer shown. No reboot was necessary.

**Comment by metanull-operator** [comment]
The Prysm Web UI can be used as well, but that takes additional setup. I believe they are considering removing support for that tool though.
