### ISSUE TITLE
Any process for installing prysmctl and exiting?

### ISSUE THREAD

**Issue by guirkgumbo** [metanull-operator/eth2-ubuntu#21]
Got up and running using v1 install instructions
Looking to install prysmctl and exit but keep getting go errors during the bazel build of prysmctl. Have you ever installed prysmctl and run the exit commands?
I already have the partial withdrawal stuff setup and working just need the prysmctl to exit according to prysm docs

**Comment by metanull-operator** [comment]
I have not. The v1 instructions were pre-merge instructions and may no longer work to get a new install up and running.

What errors are you receiving?

**Comment by guirkgumbo** [comment]
Sorry I meant that I originally used the v1 instructions way back during pre merge to get spun up and now I'm looking to exit

I couldn't figure out how to build from source from all the bazel errors I ended up just downloading the latest binary release of prysmctl and using that to run the exit commands.

Prysmctl says the voluntary exit was successful. Waiting and watching the beacha.in for the official exit.

Thanks for the guide and all the help!
