### ISSUE TITLE
Beacon-chain cannot use geth.ipc socket (degraded performance)

### ISSUE THREAD

**Issue by got3nks** [metanull-operator/eth2-ubuntu#4]
First of all thanks for the excellent guide.

Using Geth client we should get a performance boost using the IPC socket instead of the HTTP API. Unfortunately with your setup the geth.ipc file cannot be accessed by the `beacon` user.
`level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: dial unix /home/geth/geth.ipc: connect: permission denied" prefix=powchain`
Because the geth.ipc file has not the appropriate user permissions.
`srw-------  1 geth geth    0 Nov 24 00:10 geth.ipc`

Do you have any idea how to get around this issue? I could not find any parameter to change the owner of the geth.ipc file in the geth command line options. Using `chown` doesn't seem a fix either because the geth.ipc file is created at runtime by geth, from my understanding.

**Comment by metanull-operator** [comment]
Sorry for the delay on this. I do not know the answer off the top of my head, but if this is still an open issue for you, please let me know, and I can investigate further.

**Comment by got3nks** [comment]
Yes I'm still unable to use the IPC socket, but performance looks ok with HTTP API anyway.

**Comment by metanull-operator** [comment]
Looks like this is as-designed by the geth team. There are security concerns around exposing the IPC file to other users. See the following link for some discussion. Looks like one way to get around this is to put a command in the systemd service file to change the permission of the IPC file after geth starts, but there could be some timing issues around that.

https://github.com/ethereum/go-ethereum/pull/21364

I'm going to close this issue for now.
