### ISSUE TITLE
Adding a second validator later on

### ISSUE THREAD

**Issue by kyodhin** [metanull-operator/eth2-ubuntu#6]
Would be nice if there was an addon description for how to add a validator to the existing setup

**Comment by metanull-operator** [comment]
Using the same mnemonic or a different mnemonic? I'm sure both would be helpful to someone, but which are you particularly interested in?

**Comment by kyodhin** [comment]
Thx for taking the time! Although, I believe too that ppl would appreciate both, for me personally, I'm more interested in using a different mnemonic.

**Comment by metanull-operator** [comment]
Using a new mnemonic is pretty much the same process as you would have done with the first mnemonic. Use the deposit-cli tool to generate deposit data and keys. Upload deposit data to launchpad and make deposits. Import keys into validator.

The main difference between your first time and second time is that you might already have some keys in your deposit-cli folder from your first run. What I would do is backup/rename the first deposit-cli folder, then start from the beginning, downloading a new deposit-cli folder and following the instructions I already have.

Make sure you keep a copy of all mnemonics and passwords used.

That's a rough outline, but I completely understand if you'd rather see it all written out.

**Comment by kyodhin** [comment]
Thx. Yeah, I'm fairly certain that I know what I have to do. I was just trying to make really sure that it doesn't happen that my first keys somehow end up twice in there & I get slashed for running the validator twice on the network. I read that it happened to ppl with certain backup configs. 

Thx for your great write up, really appreciated it!

**Comment by metanull-operator** [comment]
I have not heard of that happening when using a single validator, particularly from an import of keys. We would have to ask the Prysm folks, but I imagine that re-importing keys that are already imported is harmless. Still, it is worth confirming. A lot of ETH is on the line, so it is best to double-check and be safe.

**Comment by kyodhin** [comment]
Okay, I have successfully added the validator:

Going through launchpad process via airgapped temp. ubuntu system. Saving keystore, deposit file & seed safely.

Then placed the keys in /home/validator/validator_keys (deleting old content before or one can rename the folder & creating a new validator_keys folder).

Import keys:

`sudo -u validator /home/validator/bin/prysm.sh validator accounts import --keys-dir=/home/validator/validator_keys`

Restart validator:

`sudo systemctl restart validator`

List all accts (optional):

`sudo -u validator /home/validator/bin/prysm.sh validator accounts list`
