### ISSUE TITLE
Adding a slasher

### ISSUE THREAD

**Issue by cin3rama** [metanull-operator/eth2-ubuntu#7]
Are you planning on adding a slasher config to the system.  I remember the prysm slasher early days wasn't optimal, but if its now ready would love to incorporate it.

**Comment by metanull-operator** [comment]
Last I heard, which was a week or two ago, Prysm was still recommending that you don't run a slasher. Specifically they said not to run a slasher on the same system you are validating on. If you wanted to run a completely separate beacon and slasher on another system, that would be OK.
Once they give the OK to run a slasher on the same system (early next year I think), then I'll add instructions.

**Comment by cin3rama** [comment]
Thank you for the response m-o.  Sounds like prysm's slasher situation hasn't changed then.  I'll keep an eye out for any updates.  ty again.
